version: '2'

services:
  nginx:
    image: "nginx"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx/etc:/etc/nginx:ro
      - ./data/nginx/log:/var/log/nginx
      - ./data/nginx/www:/usr/share/nginx/html:ro

  influxdb:
    image: "influxdb"
    volumes:
      - ./data/influxdb:/var/lib/influxdb
        
  telegraf:
    image: "nuntz/telegraf-snmp"
    volumes:
      - ./data/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    
  grafana:
    image: "grafana/grafana"
    volumes:
      - ./data/grafana/lib:/var/lib/grafana
      - ./data/grafana/log:/var/log/grafana
      - ./data/grafana/etc:/etc/grafana

  cadvisor:
    image: google/cadvisor
    command: -storage_driver=influxdb -storage_driver_db=cadvisor -storage_driver_host=influxdb:8086
    # ports:
    #   - "8088:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
